import { Area } from './area';

export const AREA_STATIC: Area[] = [
    {town_txt: "JURONG WEST"},
    {town_txt: "PUNGGOL"},
    {town_txt: "BUKIT BATOK"},
    {town_txt: "WOODLANDS"},
    {town_txt: "SENGKANG"},
    {town_txt: "CLEMENTI"},
    {town_txt: "QUEENSTOWN"},
    {town_txt: "KALLANG_WHAMPOA"},
    {town_txt: "JURONG EAST"},
    {town_txt: "CENTRAL AREA"},
    {town_txt: "ANG MO KIO"},
    {town_txt: "BEDOK"},
    {town_txt: "HOUGANG"},
    {town_txt: "BUKIT MERAH"},
    {town_txt: "TAMPINES"},
    {town_txt: "YISHUN"},
    {town_txt: "SERANGOON"},
    {town_txt: "MARINE PARADE"},
    {town_txt: "BUKIT PANJANG"},
    {town_txt: "PASIR RIS"},
    {town_txt: "CHOA CHU KANG"},
    {town_txt: "GEYLANG"},
    {town_txt: "SEMBAWANG"},
    {town_txt: "TOA PAYOH"},
    {town_txt: "BISHAN"},
    {town_txt: "BUKIT TIMAH"},
    {town_txt: "-"}
]